{
	"version": 1613329117,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/personagem-sheet0.png",
		"images/sprite-sheet0.png",
		"images/toquechao-sheet0.png",
		"images/toquechao-sheet1.png",
		"images/novainterface-sheet0.png",
		"images/cenário-sheet0.png",
		"images/carroca-sheet0.png",
		"images/degradê-sheet0.png",
		"images/inventário-sheet0.png",
		"images/moeda-sheet0.png",
		"images/botaofalar-sheet0.png",
		"images/botaopegar-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/botaodar-sheet0.png",
		"images/relógio-sheet0.png",
		"images/fundo-sheet0.png",
		"images/difrator-sheet0.png",
		"images/botão-sheet0.png",
		"images/botaousar-sheet0.png",
		"images/check-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/folk-round-by-kevin-macleod-from-filmmusic-io (1) (online-audio-converter.com).ogg",
		"media/bbc_comedy--fa_07042215 (online-audio-converter.com).ogg",
		"media/light (sting) - kevin macleod youtube audio library (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}